# Generated by Django 6.0 on 2025-12-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
